#!/bin/bash

# Server config information stored in ~/.config/restart/restartrc so that it is not stored in here...
config="$HOME/.config/restart/restartrc"
[[ ! -f "$config" ]] && mkdir -p "${config%\/*}" && touch "$config" && \
  printf '#\n# Enter server info:\n#\n# servername=<servername>\n# server=<server url>\n# sshport=<sshport - cannot be blank>\n\n# If your server port is 22 find out why it should not be and change it.\n' |tee "$config" && \
  printf 'Edit config file before rerunning.' && \
  exit

scriptname=$(realpath "$0")

#Functions
function error(){
 #read -p "$*"
 printf "Recognized commands are: \nalsa \naudio[bookshelf] - abs \nbind[9] \nchrome \ndeluge[d] \ndocker \nedit \nice[cast][2] \nminidlna (restart, force-reload, rescan) \nmpd \nnetwork/networking/network manager \nnfs \nnow \npipe(wire) \npulse(audio) \nserviio \nshout \nssh[d] \n\n"
 echo "Edit this script in nano, code, or quit?"
 select ncq in "nano" "code" "quit"; do
   case "$ncq" in
	nano ) nano /home/bvargo/bin/restart ; break;;
	code ) code /home/bvargo/bin/restart ; break;;
	quit ) echo "Done." ; break;;
   esac
 done
}


function editscript(){
if [[ "$1" == "edit" ]]; then
 (/usr/bin/nano "$scriptname")
 exit
fi
}

##############

editscript "$1"

##############

. "$config"

#unset REMOTE

remotefn() {
[[ "$(uname -n)" != "$servername" ]] && REMOTE="ssh -p $sshport $server"
printf '\nssh server name: %s\nssh server port: %s\n        ssh url: %s\n  REMOTE PREFIX: %s\n\n\n' "$servername" "$sshport" "$server" "$REMOTE"
}


#printf "\n\n\n##### REMOTE= $REMOTE\n\n\n"



if [ "$#" -eq 0 ]; then
 error

 ##A
elif [ "$1" = "alsa" ]; then
# sudo /etc/init.d/alsa-utils restart
# sudo alsa force-reload
 sudo /etc/init.d/alsa-utils status

elif [[ "$1" == "audio" ]] || [[ "$1" == "audiobookshelf" ]] || [[ "$1" == "abs" ]]; then
 remotefn && ${REMOTE:-} systemctl status audiobookshelf

##B
elif [ "$1" = "bind" ] || [ "$1" = "bind9" ]; then
# sudo systemctl restart bind9.service
# /bin/sleep 3
 systemctl status bind9.service

##C
elif [ "$1" = "chrome" ] ; then
#pkill chrome
sudo ps -A|grep chrome

##D

elif [ "$1" = "docker" ] || [ "$1" = "dockerd" ]; then
 #sudo /usr/bin/systemctl restart docker
 sudo /usr/bin/systemctl restart docker


elif [ "$1" = "deluge" ] || [ "$1" = "deluged" ]; then
# sudo systemctl restart deluged
 systemctl status deluged
 sudo ps -A |grep deluged

#elif [ "$1" = "deluge" ] || [ "$1" = "deluged" ]; then
## sudo systemctl stop deluged
# sudo pkill -9 deluged
# screen sudo -u deluge -g media deluged -d -c /var/lib/deluged/config -l /var/log/deluged/daemon.log -L debug
## sudo systemctl start deluged
# sudo ps -A |grep deluged

##E
elif [ "$1" = "edit" ]; then
 nano /home/bvargo/bin/restart

##I
elif [[ "$1" = "ice" ]] || [[ "$1" =~ "icecast" ]]; then
  systemctl status icecast
  systemctl status mpd
#sudo systemctl restart icecast2.service; systemctl status icecast2.service #; restart mpd
#elif [ "$1" = "icecast" ]; then sudo systemctl restart icecast2.service; systemctl status icecast2.service; restart mpd
#elif [ "$1" = "icecast2" ]; then sudo systemctl restart icecast2.service; systemctl status icecast2.service; restart mpd


##M
elif [ "$1" = "minidlna" ]; then
 echo "minidlna:  restart or force-reload?"
 select rfs in "status" "restart" "force-reload" "scan"; do
   case "$rfs" in
	status ) systemctl status minidlna; break ;;
	restart ) sudo systemctl restart minidlna ; systemctl status minidlna; break ;;
	force-reload ) ls -alF /var/lib/minidlna/files.db; sudo systemctl force-reload minidlna ; systemctl status minidlna; ls -alF /var/lib/minidlna/files.db; break ;;
        scan ) sudo minidlnad -r;  break ;;
   esac
 done

elif [ "$1" = "mpd" ]; then
# sudo systemctl restart mpd ;
systemctl status mpd

##N
#elif [ "$1" = "network" ] || [ "$1" = "networking" ] || [ "$1" = "network manager" ]; then sudo systemctl restart network-manager.service
#elif [ "$1" = "net" ] || [ "$1" = "network" ] || [ "$1" = "networking" ] || [ "$1" = "network manager" ]; then screen bash -c 'sudo nmcli networking off; /usr/bin/sleep 1s; sudo nmcli networking on; exit'

elif [ "$1" = "nfs" ]; then
#     if ! [[ -d /dev/shm/cache ]]
#     then
#        mkdir /dev/shm/cache
#        chown bvargo:media /dev/shm/cache
#     fi
# sudo systemctl daemon-reload
# sudo systemctl restart nfs-kernel-server
 sudo systemctl status nfs-kernel-server
 printf "$ ls -ltr /dev/shm/cache: \n"
 ls -ltr /dev/shm/cache
# sudo /etc/init.d/nfs-kernel-server restart

#elif [ "$1" = "now" ]; then
# sudo reboot now

##P
elif [ "$1" = "pipe" ] || [ "$1" = "pipewire" ] || [ "$1" = "pipewire-pulseaudio" ]; then
 /usr/bin/systemctl --user status pipewire

elif [ "$1" = "pulse" ] || [ "$1" = "pulseaudio" ] || [ "$1" = "pulse-audio" ]; then
# sudo killall pulseaudio
# pulseaudio -k
# pulseaudio --start
 pulseaudio --check

##S
elif [ "$1" = "serviio" ]; then
# sudo systemctl stop serviio.service
# sudo systemctl start serviio.service
 sudo systemctl status serviio.service

elif [ "$1" = "shout" ]; then #https://www.howtoforge.com/tutorial/ubuntu-shoutcast-server/
# echo "Attempting 'sudo killall sc_serv && sudo sc_serv &,' if it doesn't work try restarting mpd.  See also (https://www.howtoforge.com/tutorial/ubuntu-shoutcast-server/): "
# sudo killall sc_serv && sudo sc_serv &
 printf "There is no shoutcast server on this machine; status of icecast server instead!"
 systemctl status icecast2.service
# sudo systemctl restart icecast2.service #restart mpd

elif [ "$1" = "sshd" ] || [ "$1" = "ssh" ]; then
# sudo systemctl restart sshd.service
 sudo systemctl status sshd.service
# sudo systemctl restart ssh.service
 sudo systemctl status ssh.service

else
 printf "Command not found!\n"
 error
# #echo "Recognized commands are alsa, shout, deluge(d), minidlna (restart or force-reload), network/networking/network manager, nfs, now, pulse(audio)..."
# #echo "Edit this script in nano, code, or quit?"
# #select ncq in "nano" "code" "quit"; do
# #  case $ncq in
##	nano ) nano /home/bvargo/bin/restart ; break;;
##	code ) code /home/bvargo/bin/restart ; break;;
##	quit ) echo "Done." ; break;;
# #  esac
# #done
fi
